spring.application.name=integration-plateform
spring.data.mongodb.uri=mongodb://localhost:27017/integration-system
server.port=8080
jwt.secret=ajd893hkjdhaf083hkjh308y13hkjh319fhjkdfa82jd8
jwt.expiration=3600000

#prometheus and actuator

management.endpoints.web.exposure.include=health,prometheus, info,metrics