services:
  # backend:
  #   container_name: govtip
  #   build:
  #     context: ./integration-plateform
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SYSTEM_B_URL: http://system-b:8082
  #     SYSTEM_C_URL: http://system-c:8083
  #     SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/integration-system
  #   networks:
  #     - monitoring
  #   depends_on:
  #     - mongo
  #     - system-b
  #     - system-c

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: eksutra-frontend
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     API_PROXY_TARGET: http://backend:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - monitoring

  # system-b:
  #   build:
  #     context: ./system-b
  #   container_name: system-b
  #   restart: on-failure
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     MONGODB_URI: mongodb://mongo:27017/systemB
  #   depends_on:
  #     - mongo
  #   networks:
  #     - monitoring

  # system-c:
  #   build:
  #     context: ./system-c
  #   container_name: system-c
  #   restart: on-failure
  #   ports:
  #     - "8083:8083"
  #   networks:
  #     - monitoring

  # mongo:
  #   container_name: mongo
  #   image: mongo:latest
  #   restart: unless-stopped
  #   networks:
  #     - monitoring
  #   ports:
  #     - "27017:27017"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data: