kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: govt-ip-project
  source:
    repoURL: https://github.com/arpanelfranklin/EkSutra.git
    targetRevision: main
    path: monitoring/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
