kind: Service 
apiVersion: v1 
metadata: 
  name: frontend-service 
  namespace: govt-ip 
spec: 
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173        
      targetPort: 5173