apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: govt-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govtIP
  template:
    metadata:
      labels:
        app: govtIP
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsGroup: 1001
      containers:
        - name: backend
          image: arpanel/govtip:v1.1.0
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
                memory: "256Mi"
                cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"