apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: govt-ip
spec:
  selector:
    app: govtIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP