kind: Secret 
apiVersion: v1 
metadata: 
  name: secret 
  namespace: govt-ip 
type: Opaque 
stringData: 
  mongo-password: admin123
  mongo-uri: mongodb://admin:admin123@mongo-service:27017/govt-ip?authSource=admin
  mongo-uri-system-a: mongodb://admin:admin123@mongo-service:27017/SystemA?authSource=admin
  mongo-uri-system-b: mongodb://admin:admin123@mongo-service:27017/systemB?authSource=admin
  mongo-uri-system-c: mongodb://admin:admin123@mongo-service:27017/systemC?authSource=admin
